// Generated by IcedCoffeeScript 1.7.1-f
(function() {
  var fetchFormFields, iced, initBindings, main, sendFormFields, sieveFormFields, __iced_k, __iced_k_noop,
    __slice = [].slice;

  iced = {
    Deferrals: (function() {
      function _Class(_arg) {
        this.continuation = _arg;
        this.count = 1;
        this.ret = null;
      }

      _Class.prototype._fulfill = function() {
        if (!--this.count) {
          return this.continuation(this.ret);
        }
      };

      _Class.prototype.defer = function(defer_params) {
        ++this.count;
        return (function(_this) {
          return function() {
            var inner_params, _ref;
            inner_params = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
            if (defer_params != null) {
              if ((_ref = defer_params.assign_fn) != null) {
                _ref.apply(null, inner_params);
              }
            }
            return _this._fulfill();
          };
        })(this);
      };

      return _Class;

    })(),
    findDeferral: function() {
      return null;
    },
    trampoline: function(_fn) {
      return _fn();
    }
  };
  __iced_k = __iced_k_noop = function() {};

  sendFormFields = function(form_fields, subdomain) {
    return chrome.runtime.sendMessage({
      method: "put",
      form_fields: JSON.stringify(form_fields),
      subdomain: subdomain
    });
  };

  fetchFormFields = function(subdomain, defer_cb) {
    return chrome.runtime.sendMessage({
      method: "get",
      subdomain: subdomain
    }, function(resp) {
      return defer_cb(JSON.parse(resp.form_fields));
    });
  };


  /*
  Returns an associative array that maps the name of each form field
   */

  sieveFormFields = function(form_obj) {
    var arr, field, _i, _len, _ref;
    arr = {};
    _ref = $(form_obj).find("input");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      field = _ref[_i];
      if (($(field).attr("name") != null) && $(field).attr("name") !== "") {
        arr[$(field).attr("name")] = $(field).val();
      }
    }
    return arr;
  };

  initBindings = function() {
    $("form").on("submit", function(e) {
      var form_fields, subdomain;
      form_fields = sieveFormFields(this);
      subdomain = window.location.host;
      return sendFormFields(form_fields, subdomain);
    });
    return $(document).ready(function() {
      var k, plausible_form_fields, subdomain, v, ___iced_passed_deferral, __iced_deferrals, __iced_k;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      subdomain = window.location.host;
      console.log("checking for page info");
      (function(_this) {
        return (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "/home/nubela/Workspace/chrome-password-manager/src/contentscript.coffee"
          });
          fetchFormFields(subdomain, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return plausible_form_fields = arguments[0];
              };
            })(),
            lineno: 33
          }));
          __iced_deferrals._fulfill();
        });
      })(this)((function(_this) {
        return function() {
          var _results;
          if (typeof plausible_form_fields !== "undefined" && plausible_form_fields !== null) {
            _results = [];
            for (k in plausible_form_fields) {
              v = plausible_form_fields[k];
              _results.push($("input[name=" + k + "]").val(v));
            }
            return _results;
          }
        };
      })(this));
    });
  };

  main = function() {
    return initBindings();
  };

  main();

}).call(this);
