// Generated by IcedCoffeeScript 1.7.1-f
(function() {
  var init, main;

  init = function() {
    return chrome.extension.onMessage.addListener(function(req, sender, resp) {
      if (req.method === "put") {
        return localStorage[req.subdomain] = req.form_fields;
      } else if (req.method === "get") {
        if (req.subdomain in localStorage) {
          return resp({
            form_fields: localStorage[req.subdomain]
          });
        } else {
          return resp({
            form_fields: null
          });
        }
      }
    });
  };

  main = function() {
    return init();
  };

  main();

}).call(this);
